"""One Chinese stop-word list for every step that turns text into word statistics.

Why this is a module and not a local set inside each step: the corpus steps used to disagree.
``keyword`` dropped tokens shorter than two characters and nothing else, the LDA/topic-map/
topic-salience/coherence tokenisers in ``services.data_analysis`` filtered only "has a letter or
digit in it", and the word cloud carried its own small set. So the same corpus produced 特征词 like
``自己 / 一直 / 成为 / 一个 / 这个`` (measured on the 刘学州 export: several of a phase's top seven
words were pronouns and function words), and a 共词网络 whose strongest edges joined those. A topic
table whose leading words carry no meaning is not a noisy measurement — it is a measurement of
grammar.

The list is deliberately conservative, because in this domain a "filler" word can be the finding:

* **Dropped**: pronouns, demonstratives, interrogatives, aspect/particle words, copulas,
  conjunctions, prepositions, auxiliaries, quantifiers, intensifiers, and vague time words.
  These carry the shape of a sentence, not its subject.
* **Kept**: 网暴 / 暴力 / 警方 / 通报 / 律师 / 判决 / 寻亲 / 生父 / 校园 / 霸凌 / 造谣 / 私信 /
  微博 / 网友 / 粉丝 — the actors, institutions and acts a cyberbullying study is about. Also kept
  are 问题 / 声音 / 态度 and similar nouns that a generic list calls filler but which a 舆情 table
  reads as content; they stay until evidence says otherwise.

Like :mod:`analyzers.aggression`'s word lists, the incompleteness is the point of keeping it in
code: it is reviewable, and a term that should not have survived is one line to delete.
"""

import re

import jieba

__all__ = ['STOPWORDS', 'cut', 'is_meaningful', 'filter_tokens']

#: Function words only. Every entry is a word jieba can emit as one token; multi-character
#: phrases that jieba splits are not listed because they never reach a frequency table.
STOPWORDS = frozenset(
    {
        # 助词 / 语气词 — particles and sentence-final mood
        '的',
        '了',
        '着',
        '过',
        '地',
        '得',
        '吗',
        '吧',
        '呢',
        '啊',
        '呀',
        '哦',
        '噢',
        '嗯',
        '哈',
        '哇',
        '啦',
        '咯',
        '呗',
        '嘛',
        '么',
        '罢了',
        '而已',
        # 代词 — pronouns and demonstratives
        '我',
        '你',
        '他',
        '她',
        '它',
        '我们',
        '你们',
        '他们',
        '她们',
        '它们',
        '咱们',
        '本人',
        '自身',
        '自己',
        '自我',
        '大家',
        '别人',
        '人家',
        '某人',
        '这个',
        '那个',
        '这些',
        '那些',
        '这样',
        '那样',
        '这么',
        '那么',
        '这里',
        '那里',
        '此',
        '该',
        '其',
        '其它',
        '其他',
        # 疑问词 — interrogatives
        '什么',
        '怎么',
        '怎样',
        '为什么',
        '为啥',
        '哪里',
        '哪儿',
        '谁',
        '哪个',
        '哪些',
        '多少',
        '是否',
        '何',
        # 连词 / 介词 — conjunctions and prepositions
        '和',
        '与',
        '及',
        '以及',
        '或',
        '或者',
        '还是',
        '并',
        '并且',
        '而且',
        '而',
        '但',
        '但是',
        '可是',
        '不过',
        '然而',
        '虽',
        '虽然',
        '尽管',
        '因为',
        '由于',
        '所以',
        '因此',
        '于是',
        '如果',
        '假如',
        '要是',
        '即使',
        '就算',
        '除了',
        '除非',
        '至于',
        '关于',
        '对于',
        '对',
        '以',
        '于',
        '在',
        '从',
        '自',
        '向',
        '往',
        '到',
        '至',
        '由',
        '被',
        '把',
        '让',
        '给',
        '使',
        '跟',
        '同',
        '比',
        '按照',
        '根据',
        '通过',
        '经过',
        '为了',
        '为',
        '之',
        # 助动词 / 副词 — auxiliaries, negation, tense and degree
        '是',
        '不是',
        '就是',
        '算是',
        '将是',
        '真是',
        '了了',
        '没有',
        '没',
        '不',
        '别',
        '莫',
        '未',
        '非',
        '无',
        '有',
        '没有过',
        '可以',
        '可',
        '能',
        '能够',
        '可能会',
        '应该',
        '应',
        '该当',
        '必须',
        '需要',
        '要',
        '想',
        '会',
        '将',
        '会要',
        '已经',
        '已',
        '曾',
        '曾经',
        '正在',
        '在在',
        '还在',
        '就要',
        '快要',
        '马上',
        '立刻',
        '立即',
        '终于',
        '后来',
        '然后',
        '接着',
        '随后',
        '首先',
        '其次',
        '最后',
        '总之',
        '反正',
        '其实',
        '实际上',
        '事实上',
        '显然',
        '当然',
        '自然',
        '竟然',
        '居然',
        '偏偏',
        '难道',
        '几乎',
        '差不多',
        '非常',
        '十分',
        '特别',
        '尤其',
        '更',
        '最',
        '太',
        '好',
        '很',
        '真的',
        '确实',
        '的确',
        '比较',
        '稍微',
        '有点',
        '有些',
        '完全',
        '全部',
        '都',
        '也',
        '还',
        '又',
        '再',
        '就',
        '才',
        '只能',
        '只有',
        '只要',
        '不但',
        '不仅',
        '不管',
        '无论',
        '哪怕',
        # 泛化动词 — verbs that report that something was said/done without saying what
        '认为',
        '表示',
        '看到',
        '听见',
        '听到',
        '觉得',
        '感觉',
        '知道',
        '感到',
        '成为',
        '作为',
        '称为',
        '变成',
        '属于',
        '来自',
        '进行',
        '使用',
        '出现',
        '发生',
        '方面',
        # 数量 / 泛指 — quantifiers and vague measures
        '一',
        '一个',
        '一些',
        '一样',
        '一直',
        '一起',
        '一定',
        '一切',
        '每一',
        '每个',
        '各',
        '各个',
        '各自',
        '所有',
        '任意',
        '若干',
        '许多',
        '很多',
        '好多',
        '大量',
        '少许',
        '一点',
        '一点点',
        '更多',
        '最少',
        '如此',
        '这么点',
        # 时间处所泛指 — vague time and place words
        '时候',
        '时',
        '候',
        '年',
        '月',
        '日',
        '号',
        '今天',
        '昨天',
        '前天',
        '明天',
        '后天',
        '今年',
        '去年',
        '明年',
        '现在',
        '目前',
        '当前',
        '此时',
        '当时',
        '那时',
        '以前',
        '以后',
        '之后',
        '之前',
        '之际',
        '期间',
        '时代',
        '地方',
        '处',
        '里',
        '外',
        '上',
        '下',
        '中',
        '内',
        '前',
        '后',
        '左',
        '右',
        # 泛化名词 — meta-nouns that carry no subject
        '东西',
        '事情',
        '情况',
        '样子',
        '话',
        '说的',
        '来说',
        '而言',
        '之类',
        '等等',
        '等',
        '什么的',
        # 社交平台噪声 — repost chrome the regex cleaner cannot always reach
        '转发',
        '全文',
        '查看图片',
        '网页链接',
        '视频',
        '微博视频',
        'L',
        'O',
        'c',
        'http',
        'https',
        'com',
        'www',
        'cn',
        # 英文与数字噪声 — ASCII filler that survives a Chinese cut
        'ok',
        'no',
        'yes',
        'the',
        'and',
        'for',
        'you',
        'are',
        'not',
        'but',
        'can',
        'will',
        'one',
        'all',
        'ink',
        'btw',
        'em',
        'mm',
        'qaq',
        'orz',
    }
)

#: A token must contain a letter or a digit; pure punctuation is never a term.
_HAS_ALNUM = re.compile(r'[0-9A-Za-z\u4e00-\u9fff]')
_ONLY_DIGITS = re.compile(r'^[\d.,%:\-]+$')


def is_meaningful(token) -> bool:
    """Whether one token may enter a frequency table at all.

    Three rules, all of them shape rules rather than judgements about content: at least two
    characters (jieba hands back single marks and the particles the list above cannot catch when
    they are glued to nothing), some letter or digit, and not a bare number.
    """
    word = str(token or '').strip()
    if len(word) < 2:
        return False
    if not _HAS_ALNUM.search(word):
        return False
    if _ONLY_DIGITS.match(word):
        return False
    return word not in STOPWORDS


def filter_tokens(tokens) -> list:
    """Apply :func:`is_meaningful` to an iterable already cut into tokens."""
    return [token for token in tokens if is_meaningful(token)]


def cut(text) -> list:
    """Tokenise one document with the shared rule: jieba's cut, then :func:`is_meaningful`.

    Every step that counts words calls this, so a term that survives into 特征词, 显著词, 共词网络
    or a word cloud survived the same filter everywhere else too.
    """
    return filter_tokens(jieba.cut(str(text or '')))
